require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'
target 'actual' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  post_install do |installer|
    # https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1201464693
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        puts "Podfile target build config hooks applying for #{target.product_name}"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'

            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            # https://stackoverflow.com/a/48427109/986611
            config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
            config.build_settings['PROVISIONING_PROFILE'] = ''
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
            # https://support.bitrise.io/hc/en-us/articles/4406551563409-CocoaPods-frameworks-signing-issue
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
        end
      end
    end
  end
end
